import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'react-day-picker/style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col bg-zinc-950">{children}</div>
      </body>
    </html>
  )
}
